[package]
name = "rust_lib_alva_chat_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.33"
anyhow = { version = "1.0.75", features = ["backtrace"] }
num = "0.4"
image = "0.24.3"
crossbeam = "0.8"
